@url = https://localhost:7113/api
@token = bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MzRkZDJiLWRmNzYtNGYyMC1hNjcwLTgxMjk5MTRiNTdmZiIsIm5hbWUiOiJBZG1pbiIsInN1YiI6Im9jcGgyMy50ZXN0QGdtYWlsLmNvbSIsImVtYWlsIjoib2NwaDIzLnRlc3RAZ21haWwuY29tIiwianRpIjoiOTk2YWY0NGYtN2UyNC00NWYxLThiZTEtODc4NjBkM2MzM2M4IiwibmJmIjoxNjg1Mzc1NTA1LCJleHAiOjE2ODU5ODAzMDUsImlhdCI6MTY4NTM3NTUwNX0.jNIBvInSxvndy4CT5rIkM4FBh9r7n3YOzHIzb1VXF52NsuyhGJPh8Yx2ZVAxvcPEGpV_aneMUqa7fLx3W69IWg

#####

GET {{url}}/pendaftaran HTTP/1.1
Authorization: {{token}}


#####

PUT {{url}}/pendaftaran
Content-Type: application/json
Authorization: {{token}}

{
  "id": 1,
  "nama": "Aldrich Alpha Jordain",
  "jenisKelamin": 0,
  "tempatLahir": "Makassar",
  "tanggalLahir": "2015-01-01",
  "kepercayaan": 0,
  "kewarganegaraan": 0,
  "negara": null,
  "alamat": {
    "id": 1,
    "jalan": "jln. Sudirman",
    "rt": "2",
    "rw": "1",
    "keluarahan": "Tanjung Ria",
    "kecamatan": "Tanjung"
  },
  "kontak": {
    "id": 1,
    "telepon": null,
    "hp": "0811148",
    "email": null
  },
  "periodik": {
    "id": 1,
    "tinggi": 10,
    "lingkarKepala": 10,
    "berat": 20,
    "jarakKeSekolah": 1,
    "waktuTempuh": "00:30:00",
    "jumlahSaudara": 0
  },
  "ayah": {
    "id": 1,
    "nama": "Yoseph Kungkung",
    "nik": "555555",
    "tahunLahir": 1979,
    "pendidikan": 0,
    "pekerjaan": 0,
    "penghasilan": 0
  },
  "ibu": {
    "id": 2,
    "nama": "Elisabeth Hamid",
    "nik": "1112525",
    "tahunLahir": 1976,
    "pendidikan": 0,
    "pekerjaan": 0,
    "penghasilan": 0
  },
  "tempatTinggal": 0,
  "tempatTinggalLain": null,
  "modaTransportasi": 0,
  "modaTransportasiLain": null,
  "kks": null,
  "anakKe": 1,
  "kps": null,
  "pip": null,
  "tk": false,
  "userId": "3241cdfc-19a3-4561-851e-568d2ceb7f87",
  "persyaratan": []
}


####


POST {{url}}/pendaftaran/persyaratan/1 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "fileName":"file1.jpg",
    "jawaban":"noasdasd",
     "persyaratan":{
        "id": 1,
        "name":"Apalah",
        "isUpload":true,
        "description":"Aplah"
    }
}


######

PUT {{url}}/pendaftaran/persyaratan/5 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "id": 5,
  "persyaratan": {
    "id": 1,
    "name": "Apalah",
    "isUpload": true,
    "description": "Aplah"
  },
  "fileName": "fileasdadas1.jpg",
  "jawaban": "noasdasda asd asdasd"
}

