@url = https://localhost:7113/api
@token = bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMyOGE1OTdhLTA2NTgtNDQ1MC05ZGEzLTdlYWRmMjhkNmU0ZSIsIm5hbWUiOiJPY3BoMjMiLCJzdWIiOiJvY3BoMjNAZ21haWwuY29tIiwiZW1haWwiOiJvY3BoMjNAZ21haWwuY29tIiwianRpIjoiMWE0M2RkYjYtNDE1Ny00NTdlLTgwYTEtM2RkOGQyNDUwZTQzIiwibmJmIjoxNjg0NzY1NjA3LCJleHAiOjE2ODUzNzA0MDcsImlhdCI6MTY4NDc2NTYwNywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzExMy8iLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MTEzLyJ9.2Vj1Vt6zHVFfLn2DBzeYLtNPLYbyO7kfm0sL7KsIsKgJkBWIggccJhrirfIo_3lbzlKNKxxIJ4hosL321g6LBw

#####

GET {{url}}/pendaftaran HTTP/1.1
Authorization: {{token}}


#####

PUT {{url}}/pendaftaran
Content-Type: application/json
Authorization: {{token}}

{
  "id": 3,
  "nama": "Aldrich Alfa Jordain",
  "jenisKelamin": 0,
  "tempatLahir": "Makassar",
  "tanggalLahir": "2015-01-01",
  "kepercayaan": 0,
  "kewarganegaraan": 0,
  "negara": null,
  "alamat": {
    "id": 3,
    "jalan": "Perum Permata Indah",
    "rt": "2",
    "rw": "1",
    "keluarahan": "Asano",
    "kecamatan": "Abepura"
  },
  "kontak": {
    "id": 3,
    "telepon": null,
    "hp": "08111485",
    "email": null
  },
  "periodik": {
    "id": 3,
    "tinggi": 110,
    "lingkarKepala": 20,
    "berat": 130,
    "jarakKeSekolah": 1,
    "waktuTempuh": "05:20:00",
    "jumlahSaudara": 1
  },
  "ayah": {
    "id": 5,
    "nama": "Yoseph Kungkung",
    "nik": "1252525252",
    "tahunLahir": 1979,
    "pendidikan": 0,
    "pekerjaan": 0,
    "penghasilan": 0
  },
  "ibu": {
    "id": 6,
    "nama": null,
    "nik": null,
    "tahunLahir": 0,
    "pendidikan": 0,
    "pekerjaan": 0,
    "penghasilan": 0
  },
  "tempatTinggal": 0,
  "tempatTinggalLain": null,
  "modaTransportasi": 0,
  "modaTransportasiLain": null,
  "kks": null,
  "anakKe": 1,
  "kps": null,
  "pip": null,
  "tk": false,
  "userId": "c28a597a-0658-4450-9da3-7eadf28d6e4e"
}