@url = https://localhost:7113/api
@token = bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MzRkZDJiLWRmNzYtNGYyMC1hNjcwLTgxMjk5MTRiNTdmZiIsIm5hbWUiOiJBZG1pbiIsInN1YiI6Im9jcGgyMy50ZXN0QGdtYWlsLmNvbSIsImVtYWlsIjoib2NwaDIzLnRlc3RAZ21haWwuY29tIiwianRpIjoiOTk2YWY0NGYtN2UyNC00NWYxLThiZTEtODc4NjBkM2MzM2M4IiwibmJmIjoxNjg1Mzc1NTA1LCJleHAiOjE2ODU5ODAzMDUsImlhdCI6MTY4NTM3NTUwNX0.jNIBvInSxvndy4CT5rIkM4FBh9r7n3YOzHIzb1VXF52NsuyhGJPh8Yx2ZVAxvcPEGpV_aneMUqa7fLx3W69IWg

POST  {{url}}/account/register 
Content-Type: application/json

{
    "Name":"Ocph23",
    "Email":"ocph23@gmail.com",
    "Password":"Sony@77"
}

##########

POST {{url}}/account/login 
Content-Type: application/json

{
    "UserName":"ocph23.test@gmail.com",
    "Password":"Sony@77"
}

#####


#####
